name: CI

on: 
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry add pyinstaller_versionfile
          poetry add pyinstaller
        
      - name: Build Executable
        run: |
          poetry run pyivf-make_version --version ${{ github.event.release.tag_name }}.0 --company-name VorkLab --file-description="Login server emulator" --legal-copyright="Copyright © 2026 vorklab" --original-filename battlenode.exe --product-name="Battle Node" --outfile version_info
          poetry run pyinstaller main.py --onefile --noconfirm --name=battlenode-${{ github.event.release.tag_name }}-win-x64 --version-file=version_info --collect-all=tortoise --collect-all=aiomysql --collect-all=tornado --collect-all=fastapi --collect-all=uvicorn --collect-all=aiohttp --collect-all=cryptography --icon=NONE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ runner.os }} ${{ runner.arch }} Build
          path: dist/*
          include-hidden-files: false
          if-no-files-found: error

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          preserve_order: true
          overwrite_files: true
          fail_on_unmatched_files: true
          files: |
            dist/*

      
      
      
