name: CI

on: 
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        
      - name: Install Nuitka
        run: poetry add nuitka

      - name: Build Executable
        run: |
          poetry run python -m nuitka main.py --output-dir=dist --mode=onefile --assume-yes-for-downloads

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: dist/*
          include-hidden-files: false
          if-no-files-found: error

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          preserve_order: true
          overwrite_files: true
          fail_on_unmatched_files: true
          files: |
            dist/*

      
      
      
